### ISSUE TITLE
when running project report error

### ISSUE THREAD

**Issue by guoguangkun** [xyjigsaw/easy_label#20]
ModuleNotFoundError: No module named 'toolkit.sequence_tagging'

From:
File "./apiCore.py", line 26, in <module>
    from toolkit.sequence_tagging import text2entity

**Comment by guoguangkun** [comment]
It's seems like missing requirements.txt

**Comment by xyjigsaw** [comment]
Hi, there, the package is used to tag potential entities. You are free to remove it.
